### ISSUE TITLE
mac-oui.db location file is statically assigned.

### ISSUE THREAD

**Issue by phpsystems** [SYWorks/wireless-ids#1]
Hopefully, you will eventually add an option to change it, but I modified the source to the following:

from (line 4348):
appdir="/SYWorks/WIDS/"
macoui="/SYWorks/WIDS/mac-oui.db"

To:

appdir="./"
macoui="./mac-oui.db"

**Comment by SYWorks** [comment]
thks for the feedback..  :)
the reason for setting the appdir to a specific location as eventually all syworks applications will be interlink with each other such as Database, WPA-Bruteforcer, etc..
